const fs=require('fs'),path=require('path'),today=new Date().toISOString().slice(0,10),slug=today;
const feed=JSON.parse(fs.readFileSync(path.join(__dirname,'..','feed.json'),'utf8'));
if(feed.posts.find(p=>p.slug===slug)){console.log('Exists');process.exit(0)}
const pool=[[["第一次去三亚怎么玩？5天4晚完整攻略","三亚湾看日落亚龙湾游泳海棠湾免税店。海鲜去第一市场自己买旁边加工。住宿三亚湾性价比最高。","国内游"],["成都旅游攻略：除了火锅还有这些值得去","大熊猫基地要早上去、宽窄巷子+锦里+春熙路一天够、都江堰+青城山一日游。成都周边还有稻城亚丁。","国内游"],["旅行的行李打包清单：7天出游带这些就够了","证件+充电器+换洗衣服+护肤品+常用药。衣服卷起来放省空间。鞋子最多带两双。","旅行技巧"]],[["厦门旅游攻略：鼓浪屿和厦门大学怎么安排","鼓浪屿要提前买船票、住岛上才有夜景、厦门大学需要预约。曾厝垵+环岛路+沙坡尾文艺一日游。","国内游"],["云南自由行路线推荐：昆明大理丽江香格里拉","昆明2天大理2天丽江2天香格里拉2天。每个城市之间高铁1-2小时。玉龙雪山要提前买索道票。","国内游"],["机票什么时候买最便宜：比价和抢票技巧","国内提前2-3周最便宜、周二周三票价低。用比价工具不要只看一个平台。廉航行李额另买。","旅行技巧"]],[["重庆旅游必去的10个地方：魔幻3D城市","洪崖洞晚上去、轻轨穿楼李子坝、鹅岭二厂、磁器口、南山一棵树看夜景、长江索道。","国内游"],["张家界旅游攻略：天门山和森林公园怎么选","天门山1天玻璃栈道+天门洞。张家界森林公园2天袁家界杨家界金鞭溪。两个是不同景区分开买票。","国内游"],["住酒店的小妙招：这10样东西最好自己带","拖鞋浴巾一次性马桶垫洗漱用品睡衣。酒店的烧水壶不要用。带一个插排解决插座不够问题。","旅行技巧"]],[["杭州旅游攻略：西湖+灵隐寺+周边古镇","西湖一天骑行环湖最舒服。灵隐寺早上去人少。周边乌镇西塘二选一住一晚。春季龙井秋季桂花。","国内游"],["西安旅游攻略：兵马俑+城墙+回民街","兵马俑在临潼市区过去1.5小时值得看。城墙上可以骑自行车。回民街感受氛围吃去洒金桥更正宗。","国内游"],["自驾游注意事项：出发前车辆检查清单","轮胎胎压备胎状态、机油刹车油冷却液、灯光雨刷器、三角警示牌千斤顶。长途要准备车载充电器和应急物品。","旅行技巧"]],[["泰国自由行攻略：曼谷+清迈+普吉岛怎么玩","曼谷2-3天大皇宫水上市场、清迈2天山里有大象营+寺庙、普吉或苏梅3天海岛。落地签很方便。","出境游"],["日本旅游攻略：东京大阪京都怎么安排","东京3天+箱根1天+京都2天+大阪2天。买JR Pass坐新干线省钱。日本吃饭便利店性价比最高。","出境游"],["旅游拍照姿势大全：不用修图也能出片","侧身显瘦三分之一构图、逆光拍剪影、利用前景虚化、从低角度拍显高。抓拍比摆拍自然。","旅行技巧"]],[["桂林旅游攻略：漓江+阳朔+龙脊梯田","桂林市区1天象鼻山两江四湖。坐船下阳朔沿途看漓江风光。阳朔骑行+西街。龙脊梯田5月灌水10月秋收最美。","国内游"],["北京旅游攻略：故宫天安门长城怎么安排","故宫提前7天预约约满不等人。长城选慕田峪比八达岭人少。颐和园+圆明园可以一天。","国内游"],["行李箱坏了怎么应急修理：旅途中的实用技巧","轮子卡住用肥皂润滑、拉链坏了用钥匙环替代、拉杆变形不要硬拉。机场有行李打包服务。","旅行技巧"]],[["西藏旅游攻略：高原反应预防和行程安排","拉萨1-2天适应高原再出发。布达拉宫要预约、大昭寺+八廓街、纳木错一日游。红景天提前一周吃。","国内游"],["香港澳门自由行攻略：必打卡的美食和景点","香港维港+太平山+迪士尼+海洋公园。澳门大三巴+威尼斯人+官也街。香港地铁方便不用租车。","出境游"],["穷游也能玩得好：省钱旅行攻略","青旅代替酒店、淡季出行、当地公交代替打车、菜市场找美食、免费景点比收费景点更有意思。","旅行技巧"]],[["贵州旅游攻略：黄果树+千户苗寨+荔波","黄果树瀑布6-8月水量最大、西江千户苗寨住一晚看夜景、荔波小七孔水是蓝绿色的超美。","国内游"],["旅行保险有没有必要买？怎么选","出境游强烈建议买！关注医疗保额+紧急救援+航班延误+财产损失。支付宝微信都有旅行险比价。","旅行技巧"],["带老人旅游的注意事项：选对目的地很重要","选平地多的地方不要爬山。行程要松每天安排1-2个景点。注意有没有电梯和休息的地方。","旅行技巧"]]];
const idx=(new Date().getDate()-1)%pool.length,items=pool[idx];
const postTitle=items[0].tag+' | '+today;
feed.posts.unshift({slug,date:today,title:postTitle,items:items.map(i=>({title:i[0],desc:i[1],tag:i[2]}))});
feed.updated=today;
fs.writeFileSync(path.join(__dirname,'..','feed.json'),JSON.stringify(feed,null,2));
const html='<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>'+postTitle+'</title><style>*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}:root{--bg:#fafafa;--card:#fff;--text:#1a1a2e;--t2:#666;--accent:#0891b2;--border:#e5e7eb;--r:10px}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans SC",sans-serif;background:var(--bg);color:var(--text);line-height:1.7}.container{max-width:800px;margin:0 auto;padding:0 20px}header{background:var(--card);border-bottom:1px solid var(--border);padding:20px 0;margin-bottom:32px}header a{color:var(--accent);text-decoration:none;font-size:.9rem}header h1{font-size:1.3rem;margin-top:8px}.post{background:var(--card);border:1px solid var(--border);border-radius:var(--r);padding:28px}.post .date{color:var(--t2);font-size:.8rem;margin-bottom:20px}.entry{margin-bottom:24px;padding-bottom:20px;border-bottom:1px solid var(--border)}.entry:last-child{border-bottom:none}.entry h3{font-size:1rem;margin-bottom:4px}.entry p{color:var(--t2);font-size:.9rem}.tag{display:inline-block;font-size:.72rem;padding:2px 8px;border-radius:10px;margin-left:6px;background:var(--bg);color:var(--accent)}footer{text-align:center;padding:32px 20px;color:var(--t2);font-size:.8rem}@media(max-width:600px){.post{padding:18px}}</style></head><body><header><div class="container"><a href="../index.html">← 首页</a><h1>'+postTitle+'</h1></div></header><main class="container"><article class="post"><div class="date">📅 '+today+'</div>'+items.map(i=>'<div class="entry"><h3>'+i[0]+' <span class="tag">'+i[2]+'</span></h3><p>'+i[1]+'</p></div>').join('')+'</article></main><footer><p>每日更新</p></footer></body></html>';
fs.writeFileSync(path.join(__dirname,'..','posts',slug+'.html'),html);
console.log('Generated:',postTitle);
